fragment_info = {
    "Hydroxide": {'group': "organic", 'symmetry': 0},
    "Hydroxyl": {'group': "organic", 'symmetry': 1},
    "Thiol": {'group': "organic", 'symmetry': 1},
    "Carbonyl": {'group': "organic", 'symmetry': 1},
    "Alkene": {'group': "organic", 'symmetry': 1},
    "Alkyne": {'group': "organic", 'symmetry': 0},
    "Methyl": {'group': "organic", 'symmetry': 3},
    "Cyclopropyl": {'group': "organic", 'symmetry': 1},
    "Cyclobutyl": {'group': "organic", 'symmetry': 1},
    "Cyclopentyl": {'group': "organic", 'symmetry': 1},
    "Cyclopentadienyl": {'group': "organic", 'symmetry': 1},
    "Cyclohexyl": {'group': "organic", 'symmetry': 1},
    "Phenyl": {'group': "organic", 'symmetry': 2},
    "Silyl": {'group': "organic", 'symmetry': 3},
    "Amine": {'group': "organic", 'symmetry': 2},
    "Ammonium": {'group': "organic", 'symmetry': 3},
    "Nitro": {'group': "organic", 'symmetry': 2},
    "cyano": {'group': "diverse_fragments", 'symmetry': 0},
    "Phosphyl": {'group': "organic", 'symmetry': 1},
    "Phosphate": {'group': "organic", 'symmetry': 1},
    "Sulfate": {'group': "organic", 'symmetry': 1},
    "Acid(C->O)": {'group': "organic", 'symmetry': 1},
    "Acid(O->C)": {'group': "organic", 'symmetry': 1},
    "Amide(N->C)": {'group': "organic", 'symmetry': 1},
    "Amide(C->N)": {'group': "organic", 'symmetry': 1},
    "Planar_Amine": {'group': "organic", 'symmetry': 2},
    "Sulfone": {'group': "organic", 'symmetry': 1},
    "Sulfonamide": {'group': "organic", 'symmetry': 1},
    "Cycloheptane": {'group': "organic", 'symmetry': 1},
    'fluoro': {'group': 'diverse_fragments', 'symmetry': 0},
    'chloro': {'group': 'diverse_fragments', 'symmetry': 0},
    'bromo': {'group': 'diverse_fragments', 'symmetry': 0},
    'carboxy': {'group': 'diverse_fragments', 'symmetry': 2},
    'pyrazole': {'group': 'N-heterocycles', 'symmetry': 1}
}

#total, 23+37 = 60
name_map = {
'Hydroxyl': 0,
'Thiol': 1,
'Carbonyl': 2,
'Alkene': 3,
'Alkyne': 4,
'Methyl': 5, 
'Cyclopropyl': 6,
'Cyclobutyl': 7,
'Cyclopentyl': 8,
'Cyclopentadienyl': 9,
'Cyclohexyl': 10,
'Phenyl': 11,
'Amine': 12,
'Nitro': 13,
'cyano': 14,
'Ammonium': 15,
'Phosphate': 16,
'Acid(C->O)': 17,
'Acid(O->C)': 17,
'Amide(N->C)': 18,
'Amide(C->N)': 18,
'Planar_Amine': 12,
'Cycloheptane': 19,
'carboxy': 20,
'fluoro': 21,
'chloro': 21,
'bromo': 21,
'Sulfate': 22,
}